version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - FLAG=flag{sql_1nj3ct10n_1s_d4ng3r0us}
